### ISSUE TITLE
When publishing TF, how to understand the quaternion transformation?

### ISSUE THREAD

**Issue by heroacool** [facontidavide/LeGO-LOAM-BOR#10]
![image](https://user-images.githubusercontent.com/5468049/69542042-8d311700-0fc5-11ea-88de-3d5a0b83e2fb.png)

Hi @facontidavide , when reading the code, I'm confused with the quaternion transformation. 
It seems that there is no abvious geometry meaning when convert a quaternion from (qx, qy, qz, qw) to (-qy, -qz, qx, qw). Would you please explain this operation? 
Thanks!

**Comment by facontidavide** [comment]
Hi,

this code come from the original LegoLOAM and it does really piss me off. 

I don't understand that at all, there is the reason why I believe the entire thing need to be refactored. Unfortunately I have no time to do it.

**Comment by heroacool** [comment]
> Hi,
> 
> this code come from the original LegoLOAM and it does really piss me off.
> 
> I don't understand that at all, there is the reason why I believe the entire thing need to be refactored. Unfortunately I have no time to do it.

　got it. thanks.
