### ISSUE TITLE
Does this work in a multi-storey environment?

### ISSUE THREAD

**Issue by duguowei1000** [facontidavide/LeGO-LOAM-BOR#14]
Hi, pardon me as i am just starting out on research. I noticed it states "It assumes there is always a ground plane in the scan"

I have seen videos where the robot can map in a sloped environment. But will this work in a multi-storey environment? e.g multi-storey carpark?

**Comment by facontidavide** [comment]
I think so... as long as they are connected by ramps (slopes) and not stairs
