### ISSUE TITLE
Build Freeze

### ISSUE THREAD

**Issue by bugerry87** [facontidavide/LeGO-LOAM-BOR#17]
![BuildFreeze](https://user-images.githubusercontent.com/15690072/78634524-bac49000-78d6-11ea-8fd6-fde772c897c7.JPG)

The build process consumes a lot memory compared to others, until the machine freezes.
Also tried single job.

PS: Thanks, for this refactored version. I was very close to do it by my own until I found yours.

**Comment by facontidavide** [comment]
Hi,

sorry for the late reply.. I hope you found the error by now.

You run out of RAM. Just compile it with option **-j1** will work.
