### ISSUE TITLE
Bugs introduced from using Eigen

### ISSUE THREAD

**Issue by TixiaoShan** [facontidavide/LeGO-LOAM-BOR#4]
Hi @facontidavide 

Thank you for your contribution to the repository. I apologize that I didn't have time to review all those great pushes.

While looking at your code (switching from OpenCV to Eigen), I noticed there might be a few bugs in the code. OpenCV gives eigenvalue and eigenvector in reverse order as oppose to Eigen.

For example, in mapOptimization.cpp, 
```
 if (matD1(0, 0) > 3 * matD1(0, 1)) 
```
should be 
```
if (matD1(0, 2) > 3 * matD1(0, 1))
```

There might be other bugs like this when you use eigenvalue or eigenvectors.

**Comment by TixiaoShan** [comment]
I have another bag that recorded data from a boat. At the beginning the localization is fine. However, at a certain time, the localization will become completely wrong, and the base_link will begin to fly. 

The code I listed above mainly affects the matching of edge features. If you take a closer look at the saved "coeffSel" for edge feature, you will see no "coeffSel" is saved.

```
if (s > 0.1) {
    laserCloudOri->push_back(pointOri);
    coeffSel->push_back(coeff);
}
```

**Comment by facontidavide** [comment]
I see. Can you kindly share the rosbag with me? In this way I can double check that your version and mine return exactly the same result

**Comment by TixiaoShan** [comment]
My bag won't work with LeGO-LOAM because the data is captured on a boat - there is no ground at all.
